config/routes.rb
Rails.application.routes.draw do
  resources :leaderboards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ActiveRecordApi::Rest::Controller
  protect_from_forgery
  def handle_unverified_request
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeaderboardBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leaderboards/_form.html.erb
<%= form_with(model: leaderboard, local: true) do |form| %>
  <% if leaderboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
      <% leaderboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="field">
    <%= form.label :wins %>
    <%= form.text_field :wins %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leaderboards/edit.html.erb
<h1>Editing Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Show', @leaderboard %> |
<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderboards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Img</th>
      <th>String</th>
      <th>Wins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaderboards.each do |leaderboard| %>
      <tr>
        <td><%= leaderboard.name %></td>
        <td><%= leaderboard.img %></td>
        <td><%= leaderboard.string %></td>
        <td><%= leaderboard.wins %></td>
        <td><%= link_to 'Show', leaderboard %></td>
        <td><%= link_to 'Edit', edit_leaderboard_path(leaderboard) %></td>
        <td><%= link_to 'Destroy', leaderboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leaderboard', new_leaderboard_path %>

app/views/leaderboards/new.html.erb
<h1>New Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leaderboard.name %>
</p>

<p>
  <strong>Img:</strong>
  <%= @leaderboard.img %>
</p>

<p>
  <strong>String:</strong>
  <%= @leaderboard.string %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @leaderboard.wins %>
</p>

<%= link_to 'Edit', edit_leaderboard_path(@leaderboard) %> |
<%= link_to 'Back', leaderboards_path %>